## Chap 10 - Fred & Dan

In [3]:
# 10.1

import numpy as np

S0 = 100.0
K = 105.0
r = 0.08
T = 0.5
div = 0.0
u = 1.3
d = 0.8
n = 1.0

h = T/n

Su = S0 * u
Sd = S0 * d

Cu = np.maximum(Su-K,0)
Cd = np.maximum(Sd-K,0)
Pu = np.maximum(K-Su,0)
Pd = np.maximum(K-Sd,0)

delta_c = np.exp(-div*h)*((Cu-Cd)/(S0*(u-d)))
delta_p = np.exp(-div*h)*((Pu-Pd)/(S0*(u-d)))
B_c = np.exp(-r*h)*((u*Cd-d*Cu)/(u-d))
B_p = np.exp(-r*h)*((u*Pd-d*Pu)/(u-d))
price_c = delta_c * S0 + B_c
price_p = delta_p * S0 + B_p


print("For Call, delta is {0:.3f}, B is {1:.3f}, price is{2:.3f}".format(delta_c, B_c, price_c))
print("For Put, delta is {0:.3f}, B is {1:.3f}, price is{2:.3f}".format(delta_p, B_p, price_p))

For Call, delta is 0.500, B is -38.432, price is11.568
For Put, delta is -0.500, B is 62.451, price is12.451


In [4]:
# 10.4

import numpy as np
from yahoo_finance import Share

TSLA = Share('TSLA')

y1 = TSLA.get_historical('2012-1-1','2012-12-31')
y2 = TSLA.get_historical('2013-1-1','2013-12-31')
y3 = TSLA.get_historical('2014-1-1','2014-12-31')
y4 = TSLA.get_historical('2015-1-1','2015-12-31')
y5 = TSLA.get_historical('2016-1-1','2016-12-31')
list1 = [y1,y2,y3,y4,y5]
list2 = {}
list3 = []
year = 2012
for element in list1:
    temp_list = []
    for day in element:
        temp_list.append(float(day['Close']))
    price = np.array(temp_list)
    list2[str(year)]=np.diff(np.log(price))
    list3.extend(np.diff(np.log(price)))
    year += 1

total_data = np.array(list3)
print("The Annalized Volatility using 5-year data is {0:.3f} ".format(np.std(total_data)*np.sqrt(252)))
for i in range(2012, 2017):
    a = np.std(list2[str(i)][0:(len(list2[str(i)])//2)-1])*np.sqrt(252)
    b = np.std(list2[str(i)][len(list2[str(i)])//2:len(list2[str(i)])-1])*np.sqrt(252)
    print("the vol for TSLA in year {0} is: {1:.3f}".format(i,np.std(list2[str(i)])*np.sqrt(252)))
    print("The vol for TSLA in the first half of year {0} is {1:.3f} and in the second half is {2:.3f}".format(i,a,b))

The Annalized Volatility using 5-year data is 0.502 
the vol for TSLA in year 2012 is: 0.536
The vol for TSLA in the first half of year 2012 is 0.468 and in the second half is 0.600
the vol for TSLA in year 2013 is: 0.663
The vol for TSLA in the first half of year 2013 is 0.654 and in the second half is 0.669
the vol for TSLA in year 2014 is: 0.478
The vol for TSLA in the first half of year 2014 is 0.402 and in the second half is 0.543
the vol for TSLA in year 2015 is: 0.387
The vol for TSLA in the first half of year 2015 is 0.441 and in the second half is 0.316
the vol for TSLA in year 2016 is: 0.384
The vol for TSLA in the first half of year 2016 is 0.289 and in the second half is 0.462


In [6]:
# 10.6

import numpy as np

S0 = 100.0
K = 95.0
sigma = 0.30
r = 0.08
T = 1
div = 0
u = 1.3
d = 0.8
n = 2

h = T/n

spot = np.zeros((n+2,n+2))
spot[0,0] = S0

for i in range(1,n+2):
    for j in range(0,i):
        spot[j,i]=spot[j,i-1]*u
    spot[j+1,i]=spot[j,i-1]*d

call = np.maximum(spot-K,0)
print_spot=spot[0:n+1,0:n+1]
print_call=call[0:n+1,0:n+1]

delta = np.zeros((n+1,n+1))
B = np.zeros((n+1,n+1))
for i in range(n,-1,-1):
    for j in range(0,i+1):
        delta[j,i]=np.exp(-div*h)*((call[j,i+1]-call[j+1,i+1])/(spot[j,i]*(u-d)))
        B[j,i] = np.exp(-r*h)*(((u*call[j+1,i+1])-(d*call[j,i+1]))/(u-d))

print('spot_tree')
print(print_spot)
print('call_value_tree')
print(print_call)
print('delta_tree')
print(delta)
print('B_tree')
print(B)

spot_tree
[[ 100.  130.  169.]
 [   0.   80.  104.]
 [   0.    0.   64.]]
call_value_tree
[[  5.  35.  74.]
 [  0.   0.   9.]
 [  0.   0.   0.]]
delta_tree
[[ 0.7         1.          1.        ]
 [ 0.          0.225       0.77307692]
 [ 0.          0.          0.        ]]
B_tree
[[-53.80420859 -91.27499672 -91.27499672]
 [  0.         -13.83536792 -61.79797673]
 [  0.           0.           0.        ]]


In [7]:
# 10.11

import numpy as np

S0 = 100.0
K = 50.0
r = 0.07696
div = 0
T = 1

h1 = 1.0
u1 = 1.20
d1 = 1.05

Su1 = S0 * u1
Sd1 = S0 * d1
Cu1 = np.maximum(Su1-K,0.0)
Cd1 = np.maximum(Sd1-K,0.0)
delta1= np.exp(-div*h1)*((Cu1-Cd1)/(S0*(u1-d1)))
B1= np.exp(-r*h1)*((u1*Cd1-d1*Cu1)/(u1-d1))
price1 = delta1*S0 + B1
print("Answer to a: Delta is {0:.3f}, B is {1:.3f}, price is {2:.3f}".format(delta1, B1, price1))
print("There is no problem as long as d < u")

print("my guess is price2 will be greater as vega > 0")
u2 = 1.4
d2 = 0.6
Su2 = S0 * u2
Sd2 = S0 * d2
Cu2 = np.maximum(Su2-K,0.0)
Cd2 = np.maximum(Sd2-K,0.0)

delta2= np.exp(-div*h1)*((Cu2-Cd2)/(S0*(u2-d2)))
B2= np.exp(-r*h1)*((u2*Cd2-d2*Cu2)/(u2-d2))
price2 = delta2*S0 + B2
print("Answer to b: Delta is {0:.3f}, B is {1:.3f}, price is {2:.3f}".format(delta2, B2, price2))
print("")

print("my guess is price 3 will be greater as down path will then be out of money.")
u3 = 1.4
d3 = 0.4
Su3 = S0 * u3
Sd3 = S0 * d3
Cu3 = np.maximum(Su3-K,0.0)
Cd3 = np.maximum(Sd3-K,0.0)

delta3= np.exp(-div*h1)*((Cu3-Cd3)/(S0*(u3-d3)))
B3= np.exp(-r*h1)*((u3*Cd3-d3*Cu3)/(u3-d3))
price3 = delta3*S0 + B3
print("Answer to c: Delta is {0:.3f}, B is {1:.3f}, price is {2:.3f}".format(delta3, B3, price3))

Answer to a: Delta is 1.000, B is -46.296, price is 53.704
There is no problem as long as d < u
my guess is price2 will be greater as vega > 0
Answer to b: Delta is 1.000, B is -46.296, price is 53.704

my guess is price 3 will be greater as down path will then be out of money.
Answer to c: Delta is 0.900, B is -33.333, price is 56.667


In [8]:
# 10.12

import numpy as np
        
class option(object):

    def __init__(self, S, K, type):
        self.S = S
        self.K = K
        self.t = type
        self.payout = 0
        self.type = 0

    def numtype(self):
        try:
            a = {'c': 1, 'C': 1, 'p': 2, 'P': 2}
            self.type = a[self.t]
        except:
            print("invalid type")

    def get_payout(self):
        if self.type != 1 and self.type != 2:
            self.numtype()
        if self.type == 1:
            self.payout = max(self.S-self.K, 0)
        elif self.type == 2:
            self.payout = max(self.K-self.S, 0)


def main():
    S0 = 100
    K = 95
    r = 0.08
    sigma = 0.30
    div = 0.0
    T = 1.0
    N = 3.0
    h = T/N
    u = np.exp((r-div)*h+sigma*np.sqrt(h))
    d = np.exp((r-div)*h-sigma*np.sqrt(h))
    pu = (np.exp((r-div)*h)-d)/(u-d)
    pd = 1 - pu
    N = int(N)
    Firstoption = option(S0, K, 'c')
    Secondoption = option(S0, K , 'p')
    Tree = np.empty((N+1, N+1, 4), dtype=option)
    Tree[0, 0, 0] = Firstoption
    Tree[0, 0, 1] = Secondoption
    Tree[0, 0, 2] = Firstoption
    Tree[0, 0, 3] = Secondoption
    Price = np.zeros((N+1, N+1, 4))
    for k in range(0, 4):
        for i in range(1, N+1):
            for j in range(i):
                Tree[j, i, k] = option(Tree[j, i-1, k].S * u, Tree[j, i-1, k].K, Tree[j, i-1, k].t)
                Tree[j, i, k].get_payout()
            Tree[j+1, i, k] = option(Tree[j, i-1, k].S * d, Tree[j, i-1, k].K,Tree[j, i-1, k].t)
            Tree[j+1, i, k].get_payout()
    
    for i in range(N+1):
        for j in range(0,4):
            Price[i, N, j] = Tree[i, N, j].payout
    for i in range(N-1, -1, -1):
        for j in range(i+1):
            Price[j, i, 0] = max(Tree[j, i, 0].payout, np.exp(-r*h)*(pu * Price[j,i+1, 0] + pd * Price[j+1,i+1, 0]))
            Price[j, i, 1] = max(Tree[j, i, 1].payout, np.exp(-r*h)*(pu * Price[j,i+1, 1] + pd * Price[j+1,i+1, 1]))
            Price[j, i, 2] = np.exp(-r*h)*(pu * Price[j,i+1, 2] + pd * Price[j+1,i+1, 2])
            Price[j, i, 3] = np.exp(-r*h)*(pu * Price[j,i+1, 3] + pd * Price[j+1,i+1, 3])
    parity = S0 - np.exp(-r*T)*K    
    print('American Call is {0:.3f} and Put is {1:.3f}:'.format(Price[0,0,0],Price[0,0,1]))
    print('The difference between call and put is {0:.3f}, the calculated put-call parity is {1:.3f}'.format(Price[0,0,2]-Price[0,0,3], parity))
    print('European Call is {0:.3f} and Put is {1:.3f}:'.format(Price[0,0,2],Price[0,0,3]))


if __name__ == '__main__':
    main()



American Call is 18.283 and Put is 6.678:
The difference between call and put is 12.304, the calculated put-call parity is 12.304
European Call is 18.283 and Put is 5.979:


In [9]:
# 10.13

import numpy as np
        
class option(object):

    def __init__(self, S, K, type):
        self.S = S
        self.K = K
        self.t = type
        self.payout = 0
        self.type = 0

    def numtype(self):
        try:
            a = {'c': 1, 'C': 1, 'p': 2, 'P': 2}
            self.type = a[self.t]
        except:
            print("invalid type")

    def get_payout(self):
        if self.type != 1 and self.type != 2:
            self.numtype()
        if self.type == 1:
            self.payout = max(self.S-self.K, 0)
        elif self.type == 2:
            self.payout = max(self.K-self.S, 0)


def main():
    S0 = 100
    K = 95
    r = 0.08
    sigma = 0.30
    div = 0.08
    T = 1.0
    N = 3.0
    h = T/N
    u = np.exp((r-div)*h+sigma*np.sqrt(h))
    d = np.exp((r-div)*h-sigma*np.sqrt(h))
    pu = (np.exp((r-div)*h)-d)/(u-d)
    pd = 1 - pu
    N = int(N)
    Firstoption = option(S0, K, 'c')
    Secondoption = option(S0, K , 'p')
    Tree = np.empty((N+1, N+1, 4), dtype=option)
    Tree[0, 0, 0] = Firstoption
    Tree[0, 0, 1] = Secondoption
    Tree[0, 0, 2] = Firstoption
    Tree[0, 0, 3] = Secondoption
    Price = np.zeros((N+1, N+1, 4))
    for k in range(0, 4):
        for i in range(1, N+1):
            for j in range(i):
                Tree[j, i, k] = option(Tree[j, i-1, k].S * u, Tree[j, i-1, k].K, Tree[j, i-1, k].t)
                Tree[j, i, k].get_payout()
            Tree[j+1, i, k] = option(Tree[j, i-1, k].S * d, Tree[j, i-1, k].K,Tree[j, i-1, k].t)
            Tree[j+1, i, k].get_payout()
    
    for i in range(N+1):
        for j in range(0,4):
            Price[i, N, j] = Tree[i, N, j].payout
    for i in range(N-1, -1, -1):
        for j in range(i+1):
            Price[j, i, 0] = max(Tree[j, i, 0].payout, np.exp(-r*h)*(pu * Price[j,i+1, 0] + pd * Price[j+1,i+1, 0]))
            Price[j, i, 1] = max(Tree[j, i, 1].payout, np.exp(-r*h)*(pu * Price[j,i+1, 1] + pd * Price[j+1,i+1, 1]))
            Price[j, i, 2] = np.exp(-r*h)*(pu * Price[j,i+1, 2] + pd * Price[j+1,i+1, 2])
            Price[j, i, 3] = np.exp(-r*h)*(pu * Price[j,i+1, 3] + pd * Price[j+1,i+1, 3])
    parity = S0 * np.exp(-div * T) - np.exp(-r*T)*K    
    print('American Call is {0:.3f} and Put is {1:.3f}:'.format(Price[0,0,0],Price[0,0,1]))
    print('The difference between call and put is {0:.3f}, the calculated put-call parity is {1:.3f}'.format(Price[0,0,2]-Price[0,0,3], parity))
    print('European Call is {0:.3f} and Put is {1:.3f}:'.format(Price[0,0,2],Price[0,0,3]))

if __name__ == '__main__':
    main()



American Call is 14.183 and Put is 9.505:
The difference between call and put is 4.616, the calculated put-call parity is 4.616
European Call is 13.941 and Put is 9.326:


In [10]:
# 10.21

import numpy as np
        
class option(object):

    def __init__(self, S, K, type):
        self.S = S
        self.K = K
        self.t = type
        self.payout = 0
        self.type = 0

    def numtype(self):
        try:
            a = {'c': 1, 'C': 1, 'p': 2, 'P': 2}
            self.type = a[self.t]
        except:
            print("invalid type")

    def get_payout(self):
        if self.type != 1 and self.type != 2:
            self.numtype()
        if self.type == 1:
            self.payout = max(self.S-self.K, 0)
        elif self.type == 2:
            self.payout = max(self.K-self.S, 0)


def main():
    S0 = np.array([100.0,95.0])
    K = np.array([95.0,100.0])
    sigma = 0.30
    r = np.array([0.05,0.03])
    div = np.array([0.03,0.05])
    T = 3.0
    N = 3.0
    h = T/N
    u = np.exp((r-div)*h+sigma*np.sqrt(h))
    d = np.exp((r-div)*h-sigma*np.sqrt(h))
    pu = (np.exp((r-div)*h)-d)/(u-d)
    pd = 1 - pu
    N = int(N)
    Firstoption = option(S0[0], K[0], 'c')
    Secondoption = option(S0[0], K[0] , 'p')
    Thirdoption = option(S0[1],K[1],'c')
    Fourthoption = option(S0[1],K[1],'p')
    Tree = np.empty((N+1, N+1, 2, 2), dtype=option)
    Tree[0, 0, 0, 0] = Firstoption
    Tree[0, 0, 0, 1] = Thirdoption
    Tree[0, 0, 1, 0] = Secondoption
    Tree[0, 0, 1, 1] = Fourthoption
    Price = np.zeros((N+1, N+1, 2, 2))
    for l in range(0, 2):
        for k in range(0, 2):
            for i in range(1, N+1):
                for j in range(i):
                    Tree[j, i, k, l] = option(Tree[j, i-1, k, l].S * u[l], Tree[j, i-1, k, l].K, Tree[j, i-1, k, l].t)
                    Tree[j, i, k, l].get_payout()
                Tree[j+1, i, k, l] = option(Tree[j, i-1, k, l].S * d[l], Tree[j, i-1, k, l].K,Tree[j, i-1, k, l].t)
                Tree[j+1, i, k, l].get_payout()
    
    for i in range(N+1):
        for j in range(0,2):
            for k in range(0,2):
                Price[i, N, j, k] = Tree[i, N, j, k].payout
    for i in range(N-1, -1, -1):
        for j in range(i+1):
            Price[j, i, 0, 0] = np.exp(-r[0]*h)*(pu[0] * Price[j,i+1, 0, 0] + pd[0] * Price[j+1,i+1, 0, 0])
            Price[j, i, 1, 0] = np.exp(-r[0]*h)*(pu[0] * Price[j,i+1, 1, 0] + pd[0] * Price[j+1,i+1, 1, 0])
            Price[j, i, 0, 1] = np.exp(-r[1]*h)*(pu[1] * Price[j,i+1, 0, 1] + pd[1] * Price[j+1,i+1, 0, 1])
            Price[j, i, 1, 1] = np.exp(-r[1]*h)*(pu[1] * Price[j,i+1, 1, 1] + pd[1] * Price[j+1,i+1, 1, 1])
    print('European Call is {0:.3f} and Put is {1:.3f} for 100-95:'.format(Price[0,0,0,0],Price[0,0,1,0]))
    print('European Call is {0:.3f} and Put is {1:.3f} for 95-100:'.format(Price[0,0,0,1],Price[0,0,1,1]))
    

if __name__ == '__main__':
    main()




European Call is 24.006 and Put is 14.380 for 100-95:
European Call is 14.380 and Put is 24.006 for 95-100:


In [11]:
# 10.22

import numpy as np
        
class option(object):

    def __init__(self, S, K, type):
        self.S = S
        self.K = K
        self.t = type
        self.payout = 0
        self.type = 0

    def numtype(self):
        try:
            a = {'c': 1, 'C': 1, 'p': 2, 'P': 2}
            self.type = a[self.t]
        except:
            print("invalid type")

    def get_payout(self):
        if self.type != 1 and self.type != 2:
            self.numtype()
        if self.type == 1:
            self.payout = max(self.S-self.K, 0)
        elif self.type == 2:
            self.payout = max(self.K-self.S, 0)


def main():
    S0 = np.array([100.0,95.0])
    K = np.array([95.0,100.0])
    sigma = 0.30
    r = np.array([0.05,0.03])
    div = np.array([0.03,0.05])
    T = 3.0
    N = 3.0
    h = T/N
    u = np.exp((r-div)*h+sigma*np.sqrt(h))
    d = np.exp((r-div)*h-sigma*np.sqrt(h))
    pu = (np.exp((r-div)*h)-d)/(u-d)
    pd = 1 - pu
    N = int(N)
    Firstoption = option(S0[0], K[0], 'c')
    Secondoption = option(S0[0], K[0] , 'p')
    Thirdoption = option(S0[1],K[1],'c')
    Fourthoption = option(S0[1],K[1],'p')
    Tree = np.empty((N+1, N+1, 2, 2), dtype=option)
    Tree[0, 0, 0, 0] = Firstoption
    Tree[0, 0, 0, 1] = Thirdoption
    Tree[0, 0, 1, 0] = Secondoption
    Tree[0, 0, 1, 1] = Fourthoption
    Price = np.zeros((N+1, N+1, 2, 2))
    for l in range(0, 2):
        for k in range(0, 2):
            for i in range(1, N+1):
                for j in range(i):
                    Tree[j, i, k, l] = option(Tree[j, i-1, k, l].S * u[l], Tree[j, i-1, k, l].K, Tree[j, i-1, k, l].t)
                    Tree[j, i, k, l].get_payout()
                Tree[j+1, i, k, l] = option(Tree[j, i-1, k, l].S * d[l], Tree[j, i-1, k, l].K,Tree[j, i-1, k, l].t)
                Tree[j+1, i, k, l].get_payout()
    
    for i in range(N+1):
        for j in range(0,2):
            for k in range(0,2):
                Price[i, N, j, k] = Tree[i, N, j, k].payout
    for i in range(N-1, -1, -1):
        for j in range(i+1):
            Price[j, i, 0, 0] = np.maximum(Tree[j,i,0,0].payout,np.exp(-r[0]*h)*(pu[0] * Price[j,i+1, 0, 0] + pd[0] * Price[j+1,i+1, 0, 0]))
            Price[j, i, 1, 0] = np.maximum(Tree[j,i,1,0].payout,np.exp(-r[0]*h)*(pu[0] * Price[j,i+1, 1, 0] + pd[0] * Price[j+1,i+1, 1, 0]))
            Price[j, i, 0, 1] = np.maximum(Tree[j,i,0,1].payout,np.exp(-r[1]*h)*(pu[1] * Price[j,i+1, 0, 1] + pd[1] * Price[j+1,i+1, 0, 1]))
            Price[j, i, 1, 1] = np.maximum(Tree[j,i,1,1].payout,np.exp(-r[1]*h)*(pu[1] * Price[j,i+1, 1, 1] + pd[1] * Price[j+1,i+1, 1, 1]))

    print('American Call is {0:.3f} and Put is {1:.3f} for 100-95:'.format(Price[0,0,0,0],Price[0,0,1,0]))
    print('American Call is {0:.3f} and Put is {1:.3f} for 95-100:'.format(Price[0,0,0,1],Price[0,0,1,1]))
    
if __name__ == '__main__':
    main()




American Call is 24.165 and Put is 15.259 for 100-95:
American Call is 15.259 and Put is 24.165 for 95-100:
